id: 9858bfb9-3122-4d20-a9d5-585a7552d8d0
slug: newrelic-java-vertx-extensions
title: New Relic Java Instrumentation for Vert.x Extensions
description: |
  # What is Vert.x?
  Vert.x is a reactive, event-driven application framework that runs on the Java Virtual Machine (JVM). 
  It's designed to build high-performance, scalable, and resilient applications with minimal resource 
  consumption. Vert.x provides a toolkit for building reactive and distributed systems, making it suitable
  for a wide range of use cases, including web applications, microservices, and IoT (Internet of Things)
  solutions.
summary: |
  Offers comprehensive instrumentation for monitoring key components od Vert.x such as Cassandra, JDBCClient, 
  Coroutines, Kafka, RxJava, SQL Clients, Redis, MongoDB, Reactive, and Service Proxy.

level: Community

keywords:
  - nrlabs
  - nrlabs-data
  - apm
  - java
  - vertx
  - vert.x
  - sql
  - kafka
  - mssql
  - postgres
  - oracle
  - db2
  - cassandra
  - jdbc
  - redis
  - rabbitmq
  - rxjava
  - mongodb
  - reactive
  - coroutines

icon: vertx-ext.svg
authors:
  - New Relic Labs
dataSourceIds:
  - newrelic-java-vertx-extensions
documentation:
  - name: New Relic Java Instrumentation for Vert.x Extensions
    description: |
      Provides instrumentation for monitoring the Vert.x Cassandra, JDBCClient, Coroutines, Kafka, 
      RxJava, SQL Clients, Redis, MongoDB, Reactive and Service Proxy.
    url: https://github.com/newrelic/newrelic-java-vertx-extensions/tree/main#installation

dashboards:
  - java
alertPolicies:
  - java

