id: openai
displayName: OpenAI
description: |
  A lightweight tool to monitor your OpenAI workload.
icon: openai-logo.svg
install:
  primary:
    link:
      url: https://github.com/newrelic/openai-api-monitoring

keywords:
  - openai
  - gpt
  - gpt3
  - mlops

categoryTerms:
  - mlops
