id: amazon-cloudwatch-network-monitor
displayName: Amazon CloudWatch Network Monitor
description: Monitor hybrid network by Amazon CloudWatch Network Monitor
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-cloudwatch-network-monitor
icon: logo.svg