id: 69341464-f422-4617-aa9a-a4ede276b24a
slug: newrelic-java-vertx
title: New Relic Java Instrumentation for Vert.x Event Bus
description: |
  # What is Vert.x?
  Vert.x is a reactive, event-driven application framework that runs on the Java Virtual Machine (JVM). 
  It's designed to build high-performance, scalable, and resilient applications with minimal resource 
  consumption. Vert.x provides a toolkit for building reactive and distributed systems, making it suitable
  for a wide range of use cases, including web applications, microservices, and IoT (Internet of Things)
  solutions.

summary: |
  Provides instrumentation for monitoring the Vert.x Event Bus. Tracks flow across the event bus.
  Vertx-Verticles provides instrumentation for classes extends AbstractVerticle. It does this by 
  instrumenting each class that is deployed. 
  It tracks all methods except those defined by AbstractVerticle. 
  Methods not tracked: start, stop, rxStart, rxStop, config, deploymentID, getVertx, init, processArgs.

level: Community

keywords:
  - nrlabs
  - nrlabs-data
  - apm
  - java
  - vertx
  - vert.x
  - eventbus

icon: vertx.svg
authors:
  - New Relic Labs
dataSourceIds:
  - newrelic-java-vertx
documentation:
  - name: New Relic Java Instrumentation for Vert.x Event Bus
    description: |
      Provides instrumentation for Java Instrumentation for Vert.x Event Bus.
    url: https://github.com/newrelic/newrelic-java-vertx/tree/main#installation

dashboards:
  - java
alertPolicies:
  - java

