id: circleci
displayName: CircleCI
description: |
  Provides views to track the performance and health of your continuous integration and deployment pipelines.
icon: logo.png
install:
  primary:
    nerdlet:
      requiresAccount: false
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: circleci
        frameworkConfigId: circleci
keywords:
  - newrelic partner
  - devops
  - circleci
  - circle
  - cicd
  - featured
  - logs
categoryTerms:
  - newrelic partner
  - logs
