id: newrelic-java-vertx
displayName: New Relic Java Instrumentation for Vert.x Event Bus
description: |
  Provides instrumentation code for monitoring the Vert.x Event Bus. Tracks flow across the event bus.
  Vertx-Verticles provides instrumentation for classes extends AbstractVerticle. It does this by 
  instrumenting each class that is deployed. 
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: newrelic-java-vertx
      requiresAccount: false
  fallback:
    link:
      url: https://github.com/newrelic/newrelic-java-vertx/tree/main#installation
icon: vertx.svg
keywords:
  - nrlabs
  - nrlabs-data
  - apm
  - java
  - vertx
  - vert.x
  - eventbus
  - NR1_addData

